# Generated by Django 4.1.7 on 2023-04-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
        ('Eclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subjects')),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
