# Generated by Django 4.1.7 on 2023-04-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eclass', '0002_eclass_delete_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eclass',
            name='subject',
        ),
    ]
