# Generated by Django 4.1.7 on 2023-04-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_description', models.TextField()),
                ('Subject_image', models.ImageField(upload_to='subject_images/')),
            ],
        ),
    ]
