# Generated by Django 4.1.7 on 2023-04-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0002_alter_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
