# Generated by Django 4.1.7 on 2023-04-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0003_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
    ]
