# Generated by Django 4.1.7 on 2023-04-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eclass', '0003_remove_eclass_subject'),
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='eclass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eclass.eclass'),
            preserve_default=False,
        ),
    ]
