# Generated by Django 4.1.7 on 2023-04-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eclass', '0003_remove_eclass_subject'),
        ('Subjects', '0002_subjects_eclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='eclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eclass.eclass'),
        ),
    ]
