# Generated by Django 4.1.7 on 2023-04-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0003_alter_subjects_eclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='Subject_image',
            field=models.ImageField(upload_to='uploads/subject_images/'),
        ),
    ]
